### ISSUE TITLE
can i use this on next js app router 

### ISSUE THREAD

**Issue by pawitpr** [apal21/nextjs-progressbar#95] opened 2023-06-27 12:11 UTC
any known how to implement this in nextjs app router, pls need help

**Comment by imranbarbhuiya** [comment] 2023-06-27 12:29
Duplicate of #86

**Closed by imranbarbhuiya** 2023-06-27 12:29 UTC

**Comment by ChetSocio** [comment] 2023-06-28 08:27
You can create loading.ts file that comes on nextjs app directory. You donot need to use this package anymore
